### ISSUE TITLE
Invalid collection name regex

### ISSUE THREAD

**Issue by ArjixWasTaken** [gsoft-inc/wl-extensions-mongo#66]
**Describe the bug**
The regex you are using in the [`MongoCollection` attribute](https://github.com/gsoft-inc/wl-extensions-mongo/blob/main/src/Workleap.Extensions.Mongo.Abstractions/MongoCollectionAttribute.cs#L8) does not allow kebab case.
But mongo clearly allows kebab casing, as it works fine.

**To Reproduce**
1. Make a model for your mongo collection
2. Decorate it with `[MongoCollection("name-with-dash")]`
3. See error

**Expected behavior**
To not have the error

**Environment (please complete the following information):**
 - OS: Irrelevant
 - Version: [1.6.0](https://github.com/gsoft-inc/wl-extensions-mongo/releases/tag/1.6.0)
 - IDE: Irrelevant

**Additional context**
My temporary solution was to replace the regex using [Harmony](https://github.com/pardeike/Harmony).
```csharp
MongoCollectionAttributePatch.Patch(new Harmony("my-harmony-patch"));

internal static class MongoCollectionAttributePatch
{
    public static void Patch(Harmony harmony)
    {
        harmony.Patch(
            original: AccessTools.Constructor(typeof(MongoCollectionAttribute), new [] { typeof(string) }),
            transpiler: new HarmonyMethod(AccessTools.Method(typeof(MongoCollectionAttributePatch), nameof(ConstructorTranspiler)))
        );
    }

    public static Regex ActuallyValidRegex = new Regex("^[-a-zA-Z][-a-zA-Z0-9]{0,63}$", RegexOptions.Compiled);
    
    /**
     * Patches `Workleap.Extensions.Mongo.Abstractions.MongoCollectionAttribute` at runtime to allow dashes (-) in collection names.
     * This may break if a different version of `Workleap.Extensions.Mongo` is used.
     */
    static IEnumerable<CodeInstruction> ConstructorTranspiler(IEnumerable<CodeInstruction> instructions)
    {
        var regexRef = AccessTools.Field(typeof(MongoCollectionAttributePatch), nameof(ActuallyValidRegex));
        
        foreach (var instr in instructions)
        {
            yield return instr;
            if (instr.opcode == OpCodes.Ldsfld &&
                instr.operand is FieldInfo { Name: "ValidNameRegex" })
            {
                instr.operand = regexRef;
            }
        }
    }
}
```

**Comment by ArjixWasTaken** [comment]
Although, having harmony messes up my debugger, so I can no longer use a debugger with this solution in place.
(the Rider debugger)

**Comment by cptCloud** [comment]
Thank you for taking the time to report it.

**Comment by ArjixWasTaken** [comment]
Supporting kebab case is not planned?

**Comment by ArjixWasTaken** [comment]
Here is an improvement of your regex based on the mongo docs.
```javascript
/^(?<!system\.)[_a-zA-Z][_a-zA-Z0-9-]{0,63}$/
```
![image](https://github.com/gsoft-inc/wl-extensions-mongo/assets/53124886/5deef372-1238-4c65-9a58-e53a88f8dcb3)

**Comment by ArjixWasTaken** [comment]
The arbitrary limitation of 64 characters that you impose should also go away.
But that would be impossible to do via regex alone, since you'd have to take the database name to calculate if it is valid.

> The namespace length limit for unsharded collections and views is 255 bytes, and 235 bytes for sharded collections. For a collection or a view, the namespace includes the database name, the dot (.) separator, and the collection/view name (e.g. [database].[collection]).

**Comment by meziantou** [comment]
This library is opiniated. It doesn't need to accept everything accepted by mongodb, but the intersection of [Mongo limitations](https://www.mongodb.com/docs/manual/reference/limits/#mongodb-limit-Restriction-on-Collection-Names) and what we want to accept. That's what the current validation does. We could update the regex, but we don't have a need for it yet.

**Comment by ArjixWasTaken** [comment]
Would you accept a PR?
If so, are there contribution guidelines I should follow?

**Comment by Gcaya** [comment]
Thanks for the quality feedback @ArjixWasTaken, the thing currently is that internally we haven't fully defined our contribution policy and the whole process around it. It's something we need to look at as a company, but there's no defined ETA at the moment.

**Comment by ArjixWasTaken** [comment]
That's sad to hear, once you have defined those guidelines, please notify me by using my github handle.
I feel like I have many things I want to contribute, but I don't want to maintain a fork of my own.
